spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: movie-service-route
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: serie-service-route
          uri: lb://serie-service
          predicates:
            - Path=/series/**
        - id: catalog-service-route
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**

server:
  port: 8080

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
    instance:
      preferIpAddress: true
